name: Lotto Prediction
on:
  schedule:
    - cron: '0 9 * * 5'  # Piątek 11:00 czasu polskiego
  workflow_dispatch:  # Umożliwia ręczne uruchomienie
jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: python lotto_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
